$terminal = kitty
$browser = firefox -p personal
$school = firefox -p school
$menu = rofi -show drun -show-icons
$screenshot = grim -g "$(slurp -d)" - | wl-copy
$lock = pidof hyprlock || hyprlock > /dev/null
$powermenu = rofi -show menu -modi "menu:~/.local/bin/powermenu --choices=shutdown/reboot/lockscreen"
$nighton = busctl --user -- set-property rs.wl-gammarelay / rs.wl.gammarelay Temperature q 4000
$nightoff = busctl --user -- set-property rs.wl-gammarelay / rs.wl.gammarelay Temperature q 6500
