exec-once = mako
exec-once = waybar
exec-once = wl-gammarelay-rs
exec-once = swww-daemon
exec-once = hypridle

exec = wl-paste --watch cliphist store

# Dark mode
exec = gsettings set org.gnome.desktop.interface gtk-theme "YOUR_DARK_GTK3_THEME"   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
